# Generated by Django 5.0.1 on 2025-07-08 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CuponDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=150, unique=True)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('revendedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cupon_descuento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
