# Generated by Django 5.2.5 on 2025-08-26 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_producto_stock_cupondescuento"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="registrado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Para usuarios con rol CLIENTE, indica el revendedor que los registró.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes_registrados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
