# Generated by Django 5.2.3 on 2025-06-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_customuser_es_distribuidor_exclusivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="domicilio",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="ciudad",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
