# Generated by Django 5.2.3 on 2025-06-15 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_customuser_domicilio_alter_customuser_ciudad"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="domicilio",
        ),
    ]
