# Generated by Django 5.2.3 on 2025-06-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_customuser_domicilio"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="domicilio",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
