# Generated by Django 5.2.3 on 2025-06-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_customuser_domicilio"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="provincia",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
